# Python package
# Create and test a Python package on multiple Python versions.
# Add steps that analyze code, save the dist with the build record, publish to a PyPI-compatible index, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/python

trigger:
- main

pool:
  vmImage: windows-latest

steps:



- task: CmdLine@2
  inputs:
    script: |
      echo %python --version%
      pip install -r requirements.txt
  displayName: 'Install dependencies'

- task: CmdLine@2
  inputs:
    script: |
      echo %cd%
      for /r %%i in (D:\a\1\s\login_test.py) do "python.exe" %%i
  displayName: 'Run tests'
