
Skip to content
Pull requests
Issues
Marketplace
Explore
@philipsutton
philipsutton /
automated-tests
Public

Code
Issues
Pull requests
Actions
Projects
Wiki
Security
Insights

    Settings

automated-tests/azure-pipelines.yml
@philipsutton
philipsutton Update azure-pipelines.yml for Azure Pipelines
Latest commit e29418f 35 minutes ago
History
2 contributors
@philip-sutton4
@philipsutton
49 lines (38 sloc) 1012 Bytes
# Python package
# Create and test a Python package on multiple Python versions.
# Add steps that analyze code, save the dist with the build record, publish to a PyPI-compatible index, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/python

trigger:
- main

pool:
  name: 'agent1'
#strategy:
#  matrix:
#    Python27:
 #     python.version: '2.7'
 #   Python35:
 #     python.version: '3.5'
 #   Python36:
 #     python.version: '3.6'
 #   Python37:
 #     python.version: '3.7'

steps:





- script: |
    python -m pip install --upgrade pip
    pip install -r requirements.txt
  displayName: 'Install dependencies'

- task: CmdLine@2
  inputs:
    script: |
      echo %cd%
      for /r %%i in (*.py) do "python.exe" %%i
  displayName: 'Run tests'

#- script: |
#    pip install pytest pytest-azurepipelines
#    pytest
#  displayName: 'pytest'

- task: PublishTestResults@2
  inputs:
    testResultsFormat: 'JUnit'
    testResultsFiles: '**/TEST-*.xml'
    failTaskOnFailedTests: true
Footer
© 2022 GitHub, Inc.
Footer navigation

    Terms
    Privacy
    Security
    Status
    Docs
    Contact GitHub
    Pricing
    API
    Training
    Blog
    About

You have no unread notifications